apiVersion: v1
kind: ConfigMap
metadata:
  name: shortener-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/shortener"
  SPRING_DATASOURCE_USERNAME: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"